### PR TITLE
Fixed missing tooltip for text field parameters in build forms

### PR DESCRIPTION
**Pull request by campos-ddc**

### CODE REVIEW

**Comment by campos-ddc** [comment]
image

This adds the tooltip thing to text paramaters.

**Comment by campos-ddc** [comment]
I would like to make the "?" info image clickable, since that link in the tooltip is quite useless without it.

Do you guys know how to do that? I imagine it would need more changes to the jinja2 template I touched in this PR, but probably some css changes to the tooltip class too.

**Comment by campos-ddc** [comment]
Also, looks like some tests failed here, and I think they are not related to my change.

Could you take a look?

**Review by Mowinski — APPROVED** [review]

**Comment by Mowinski** [comment]
Looks good but could you rebase it with staging to fix tests? :)

**Comment by campos-ddc** [comment]
rebased

**Pull request merged**
