### PR TITLE
[CDSK-554] Change the confirmation text from 'stop this build' button

### PR DESCRIPTION
**Pull request by Mowinski**
'Stop this build' should have confirmation text which describes the action of this button

New stop build dialog:
stop_build

New stop entire build chain dialog
stop_entire_build_chain

progress

### CODE REVIEW

**Review by warcholprzemo — APPROVED** [review]

**Comment by campos-ddc** [comment]
"Are you sure you want to cancel?"
`Cancel` / `OK`

Can we change the text on those buttons? I guess the better modal screen makes sense sooner than later :)

**Comment by campos-ddc** [comment]
I think that the "No" button should use the standard grey color, like these:

image

**Comment by Mowinski** [comment]
Small update 
buttons

**Review by warcholprzemo — COMMENTED** [review]
Goo job

**Review by warcholprzemo — APPROVED** [review]

**Review by campos-ddc — APPROVED** [review]

**Pull request merged**
