### PR TITLE
[CDSK-935] Create a mechanism to change stylesheet between staging and production

### PR DESCRIPTION
**Pull request by Mowinski**
I've created a mechanism to switch between two different schemas in CSS.

On staging before starting katana must set `KATANA_CONFIGURATION` on `staging` value.

Staging:
staging

Production:
production

### CODE REVIEW

**Comment by campos-ddc** [comment]
I think we should use `BuildmasterConfig` to set this option, instead of environment variables.

We always start Katana through our buildmaster repo, that contains a master.cfg file:

https://ono.unity3d.com/katana/buildmaster/files/259aaeafa03ce798a02424326b380e3b8160ad5e/master.cfg

Notice that we set a bunch of variables (such as `c['slaves'], c['title'], etc) and some of them are imported from a `buildmaster_configuration` module. This module is where we keep all differences between staging and production (by keeping separate branches): https://gitlab.internal.unity3d.com/CDS/Katana/buildmaster_configuration

Ideally, this UI configuration should be in that repo, and be passed to Katana through master.cfg in `buildmaster`

**Comment by Mowinski** [comment]
I've added a new option to `master.cfg` file. You can set a different color schema by setting in config file this attribute `c['environment'] = 'production'` or `c['environment'] = 'staging'`. What do you think about this solution?

Should I add this field to master.cfg in buildmaster config repository?

**Comment by warcholprzemo** [comment]
Do we get rid of the developer color? For me it's ok, just asking.
current_dev

EDIT: Ah, I've figured out that if we setup `c['environment'] = ''` in master.cfg we can see dev mode :-)
If we put `c['environment'] = 'production'` we can see production colors. Good job :+1:

**Review by warcholprzemo — APPROVED** [review]

**Comment by campos-ddc** [comment]
@Mowinski yes, that would be great

`master.cfg` in `buildmaster` should have a `c['environment'] = serversetting.get_environment()`, while the actual production/staging string should be set in this file:

https://gitlab.internal.unity3d.com/CDS/Katana/buildmaster_configuration/blob/master/buildmaster_configuration/serversettings.py

With different values for the `staging` and `master` (production) branches

**Pull request merged**
